import { Component, OnInit, ViewChild } from '@angular/core';
import { FormGroup, FormControl, Validators } from '@angular/forms';
import { MatPaginator } from '@angular/material/paginator';
import { MatSort } from '@angular/material/sort';
import { MatTableDataSource } from '@angular/material/table';
import { Router } from '@angular/router';

@Component({
  selector: 'app-class',
  templateUrl: './class.component.html',
  styleUrls: ['./class.component.scss']
})
export class ClassComponent implements OnInit {
  @ViewChild(MatSort) sort: MatSort;
  paginator: MatPaginator;
  @ViewChild(MatPaginator) set matPaginator(mp: MatPaginator) {
    this.paginator = mp;
    this.setDataSourceAttributes();
  }
  data: any = [
    {
      'enrollmentNumber': '1',
      'Student': 'Jess Medina',
      'Assignment 1': 'AA',
      'Assignment 2': 'CC',
      'Assignment 3': 'DA',
      'Assignment 4': 'BB',
      'Assignment 5': 'AA',
      'Assignment 6': 'CC',
      'Assignment 7': 'AA',
      'Assignment 8': 'DC',
      'Assignment 9': 'AA',
      'Assignment 10': 'AA',
      'Assignment 11': 'DD',
      'Assignment 12': 'AA',
      'Assignment 13': 'AA',
      'Assignment 14': 'AB',
      'Assignment 15': 'AD',
      'Assignment 16': 'CA',
      'Assignment 17': 'AA',
      'Assignment 18': 'FF',
      'Assignment 19': 'BA',
      'Assignment 20': 'AA',
    },
    {
      'enrollmentNumber': '2',
      'Student': 'Benito Ray',
      'Assignment 1': 'AA',
      'Assignment 2': 'BB',
      'Assignment 3': 'DA',
      'Assignment 4': 'CC',
      'Assignment 5': 'AA',
      'Assignment 6': 'CC',
      'Assignment 7': 'AA',
      'Assignment 8': 'AA',
      'Assignment 9': 'AA',
      'Assignment 10': 'DC',
      'Assignment 11': 'AD',
      'Assignment 12': 'AA',
      'Assignment 13': 'AB',
      'Assignment 14': 'CA',
      'Assignment 15': 'DD',
      'Assignment 16': 'AA',
      'Assignment 17': 'AA',
      'Assignment 18': 'BA',
      'Assignment 19': 'AA',
      'Assignment 20': 'FF',
    },
    {
      'enrollmentNumber': '3',
      'Student': 'Kirby Miles',
      'Assignment 1': 'AA',
      'Assignment 2': 'AA',
      'Assignment 3': 'CC',
      'Assignment 4': 'CD',
      'Assignment 5': 'AA',
      'Assignment 6': 'AA',
      'Assignment 7': 'CC',
      'Assignment 8': 'AA',
      'Assignment 9': 'AA',
      'Assignment 10': 'AA',
      'Assignment 11': 'DC',
      'Assignment 12': 'DD',
      'Assignment 13': 'AA',
      'Assignment 14': 'AA',
      'Assignment 15': 'AD',
      'Assignment 16': 'AB',
      'Assignment 17': 'FF',
      'Assignment 18': 'CA',
      'Assignment 19': 'AA',
      'Assignment 20': 'BA',
    },
    {
      'enrollmentNumber': '4',
      'Student': 'Aimie Rooney',
      'Assignment 1': 'CC',
      'Assignment 2': 'CC',
      'Assignment 3': 'AA',
      'Assignment 4': 'AA',
      'Assignment 5': 'DD',
      'Assignment 6': 'AA',
      'Assignment 7': 'AA',
      'Assignment 8': 'DC',
      'Assignment 9': 'CD',
      'Assignment 10': 'AA',
      'Assignment 11': 'AA',
      'Assignment 12': 'AD',
      'Assignment 13': 'FF',
      'Assignment 14': 'AA',
      'Assignment 15': 'BA',
      'Assignment 16': 'AA',
      'Assignment 17': 'AA',
      'Assignment 18': 'AB',
      'Assignment 19': 'AA',
      'Assignment 20': 'CA',
    },
    {
      'enrollmentNumber': '5',
      'Student': 'Rebecca Smith',
      'Assignment 1': 'CC',
      'Assignment 2': 'CC',
      'Assignment 3': 'AA',
      'Assignment 4': 'DD',
      'Assignment 5': 'DC',
      'Assignment 6': 'AA',
      'Assignment 7': 'AA',
      'Assignment 8': 'CD',
      'Assignment 9': 'AA',
      'Assignment 10': 'AA',
      'Assignment 11': 'AD',
      'Assignment 12': 'AA',
      'Assignment 13': 'AA',
      'Assignment 14': 'AA',
      'Assignment 15': 'FF',
      'Assignment 16': 'AA',
      'Assignment 17': 'BA',
      'Assignment 18': 'AB',
      'Assignment 19': 'AA',
      'Assignment 20': 'CA',
    },
    {
      'enrollmentNumber': '6',
      'Student': 'Jess Medina',
      'Assignment 1': 'AA',
      'Assignment 2': 'CC',
      'Assignment 3': 'DA',
      'Assignment 4': 'BB',
      'Assignment 5': 'AA',
      'Assignment 6': 'CC',
      'Assignment 7': 'AA',
      'Assignment 8': 'DC',
      'Assignment 9': 'AA',
      'Assignment 10': 'AA',
      'Assignment 11': 'DD',
      'Assignment 12': 'AA',
      'Assignment 13': 'AA',
      'Assignment 14': 'AB',
      'Assignment 15': 'AD',
      'Assignment 16': 'CA',
      'Assignment 17': 'AA',
      'Assignment 18': 'FF',
      'Assignment 19': 'BA',
      'Assignment 20': 'AA',
    },
    {
      'enrollmentNumber': '7',
      'Student': 'Benito Ray',
      'Assignment 1': 'AA',
      'Assignment 2': 'BB',
      'Assignment 3': 'DA',
      'Assignment 4': 'CC',
      'Assignment 5': 'AA',
      'Assignment 6': 'CC',
      'Assignment 7': 'AA',
      'Assignment 8': 'AA',
      'Assignment 9': 'AA',
      'Assignment 10': 'DC',
      'Assignment 11': 'AD',
      'Assignment 12': 'AA',
      'Assignment 13': 'AB',
      'Assignment 14': 'CA',
      'Assignment 15': 'DD',
      'Assignment 16': 'AA',
      'Assignment 17': 'AA',
      'Assignment 18': 'BA',
      'Assignment 19': 'AA',
      'Assignment 20': 'FF',
    },
    {
      'enrollmentNumber': '8',
      'Student': 'Kirby Miles',
      'Assignment 1': 'AA',
      'Assignment 2': 'AA',
      'Assignment 3': 'CC',
      'Assignment 4': 'CD',
      'Assignment 5': 'AA',
      'Assignment 6': 'AA',
      'Assignment 7': 'CC',
      'Assignment 8': 'AA',
      'Assignment 9': 'AA',
      'Assignment 10': 'AA',
      'Assignment 11': 'DC',
      'Assignment 12': 'DD',
      'Assignment 13': 'AA',
      'Assignment 14': 'AA',
      'Assignment 15': 'AD',
      'Assignment 16': 'AB',
      'Assignment 17': 'FF',
      'Assignment 18': 'CA',
      'Assignment 19': 'AA',
      'Assignment 20': 'BA',
    },
    {
      'enrollmentNumber': '9',
      'Student': 'Aimie Rooney',
      'Assignment 1': 'CC',
      'Assignment 2': 'CC',
      'Assignment 3': 'AA',
      'Assignment 4': 'AA',
      'Assignment 5': 'DD',
      'Assignment 6': 'AA',
      'Assignment 7': 'AA',
      'Assignment 8': 'DC',
      'Assignment 9': 'CD',
      'Assignment 10': 'AA',
      'Assignment 11': 'AA',
      'Assignment 12': 'AD',
      'Assignment 13': 'FF',
      'Assignment 14': 'AA',
      'Assignment 15': 'BA',
      'Assignment 16': 'AA',
      'Assignment 17': 'AA',
      'Assignment 18': 'AB',
      'Assignment 19': 'AA',
      'Assignment 20': 'CA',
    },
    {
      'enrollmentNumber': '10',
      'Student': 'Grady Piper',
      'Assignment 1': 'CC',
      'Assignment 2': 'CC',
      'Assignment 3': 'AA',
      'Assignment 4': 'DD',
      'Assignment 5': 'DC',
      'Assignment 6': 'AA',
      'Assignment 7': 'AA',
      'Assignment 8': 'CD',
      'Assignment 9': 'AA',
      'Assignment 10': 'AA',
      'Assignment 11': 'AD',
      'Assignment 12': 'AA',
      'Assignment 13': 'AA',
      'Assignment 14': 'AA',
      'Assignment 15': 'FF',
      'Assignment 16': 'AA',
      'Assignment 17': 'BA',
      'Assignment 18': 'AB',
      'Assignment 19': 'AA',
      'Assignment 20': 'CA',
    },
    {
      'enrollmentNumber': '11',
      'Student': 'Jess Medina',
      'Assignment 1': 'AA',
      'Assignment 2': 'CC',
      'Assignment 3': 'DA',
      'Assignment 4': 'BB',
      'Assignment 5': 'AA',
      'Assignment 6': 'CC',
      'Assignment 7': 'AA',
      'Assignment 8': 'DC',
      'Assignment 9': 'AA',
      'Assignment 10': 'AA',
      'Assignment 11': 'DD',
      'Assignment 12': 'AA',
      'Assignment 13': 'AA',
      'Assignment 14': 'AB',
      'Assignment 15': 'AD',
      'Assignment 16': 'CA',
      'Assignment 17': 'AA',
      'Assignment 18': 'FF',
      'Assignment 19': 'BA',
      'Assignment 20': 'AA',
    },
    {
      'enrollmentNumber': '12',
      'Student': 'Benito Ray',
      'Assignment 1': 'AA',
      'Assignment 2': 'BB',
      'Assignment 3': 'DA',
      'Assignment 4': 'CC',
      'Assignment 5': 'AA',
      'Assignment 6': 'CC',
      'Assignment 7': 'AA',
      'Assignment 8': 'AA',
      'Assignment 9': 'AA',
      'Assignment 10': 'DC',
      'Assignment 11': 'AD',
      'Assignment 12': 'AA',
      'Assignment 13': 'AB',
      'Assignment 14': 'CA',
      'Assignment 15': 'DD',
      'Assignment 16': 'AA',
      'Assignment 17': 'AA',
      'Assignment 18': 'BA',
      'Assignment 19': 'AA',
      'Assignment 20': 'FF',
    },
    {
      'enrollmentNumber': '13',
      'Student': 'Kirby Miles',
      'Assignment 1': 'AA',
      'Assignment 2': 'AA',
      'Assignment 3': 'CC',
      'Assignment 4': 'CD',
      'Assignment 5': 'AA',
      'Assignment 6': 'AA',
      'Assignment 7': 'CC',
      'Assignment 8': 'AA',
      'Assignment 9': 'AA',
      'Assignment 10': 'AA',
      'Assignment 11': 'DC',
      'Assignment 12': 'DD',
      'Assignment 13': 'AA',
      'Assignment 14': 'AA',
      'Assignment 15': 'AD',
      'Assignment 16': 'AB',
      'Assignment 17': 'FF',
      'Assignment 18': 'CA',
      'Assignment 19': 'AA',
      'Assignment 20': 'BA',
    },
    {
      'enrollmentNumber': '14',
      'Student': 'Aimie Rooney',
      'Assignment 1': 'CC',
      'Assignment 2': 'CC',
      'Assignment 3': 'AA',
      'Assignment 4': 'AA',
      'Assignment 5': 'DD',
      'Assignment 6': 'AA',
      'Assignment 7': 'AA',
      'Assignment 8': 'DC',
      'Assignment 9': 'CD',
      'Assignment 10': 'AA',
      'Assignment 11': 'AA',
      'Assignment 12': 'AD',
      'Assignment 13': 'FF',
      'Assignment 14': 'AA',
      'Assignment 15': 'BA',
      'Assignment 16': 'AA',
      'Assignment 17': 'AA',
      'Assignment 18': 'AB',
      'Assignment 19': 'AA',
      'Assignment 20': 'CA',
    },
    {
      'enrollmentNumber': '15',
      'Student': 'Grady Piper',
      'Assignment 1': 'CC',
      'Assignment 2': 'CC',
      'Assignment 3': 'AA',
      'Assignment 4': 'DD',
      'Assignment 5': 'DC',
      'Assignment 6': 'AA',
      'Assignment 7': 'AA',
      'Assignment 8': 'CD',
      'Assignment 9': 'AA',
      'Assignment 10': 'AA',
      'Assignment 11': 'AD',
      'Assignment 12': 'AA',
      'Assignment 13': 'AA',
      'Assignment 14': 'AA',
      'Assignment 15': 'FF',
      'Assignment 16': 'AA',
      'Assignment 17': 'BA',
      'Assignment 18': 'AB',
      'Assignment 19': 'AA',
      'Assignment 20': 'CA',
    },
    {
      'enrollmentNumber': '16',
      'Student': 'Jess Medina',
      'Assignment 1': 'AA',
      'Assignment 2': 'CC',
      'Assignment 3': 'DA',
      'Assignment 4': 'BB',
      'Assignment 5': 'AA',
      'Assignment 6': 'CC',
      'Assignment 7': 'AA',
      'Assignment 8': 'DC',
      'Assignment 9': 'AA',
      'Assignment 10': 'AA',
      'Assignment 11': 'DD',
      'Assignment 12': 'AA',
      'Assignment 13': 'AA',
      'Assignment 14': 'AB',
      'Assignment 15': 'AD',
      'Assignment 16': 'CA',
      'Assignment 17': 'AA',
      'Assignment 18': 'FF',
      'Assignment 19': 'BA',
      'Assignment 20': 'AA',
    },
    {
      'enrollmentNumber': '17',
      'Student': 'Benito Ray',
      'Assignment 1': 'AA',
      'Assignment 2': 'BB',
      'Assignment 3': 'DA',
      'Assignment 4': 'CC',
      'Assignment 5': 'AA',
      'Assignment 6': 'CC',
      'Assignment 7': 'AA',
      'Assignment 8': 'AA',
      'Assignment 9': 'AA',
      'Assignment 10': 'DC',
      'Assignment 11': 'AD',
      'Assignment 12': 'AA',
      'Assignment 13': 'AB',
      'Assignment 14': 'CA',
      'Assignment 15': 'DD',
      'Assignment 16': 'AA',
      'Assignment 17': 'AA',
      'Assignment 18': 'BA',
      'Assignment 19': 'AA',
      'Assignment 20': 'FF',
    },
    {
      'enrollmentNumber': '18',
      'Student': 'Kirby Miles',
      'Assignment 1': 'AA',
      'Assignment 2': 'AA',
      'Assignment 3': 'CC',
      'Assignment 4': 'CD',
      'Assignment 5': 'AA',
      'Assignment 6': 'AA',
      'Assignment 7': 'CC',
      'Assignment 8': 'AA',
      'Assignment 9': 'AA',
      'Assignment 10': 'AA',
      'Assignment 11': 'DC',
      'Assignment 12': 'DD',
      'Assignment 13': 'AA',
      'Assignment 14': 'AA',
      'Assignment 15': 'AD',
      'Assignment 16': 'AB',
      'Assignment 17': 'FF',
      'Assignment 18': 'CA',
      'Assignment 19': 'AA',
      'Assignment 20': 'BA',
    },
    {
      'enrollmentNumber': '19',
      'Student': 'Aimie Rooney',
      'Assignment 1': 'CC',
      'Assignment 2': 'CC',
      'Assignment 3': 'AA',
      'Assignment 4': 'AA',
      'Assignment 5': 'DD',
      'Assignment 6': 'AA',
      'Assignment 7': 'AA',
      'Assignment 8': 'DC',
      'Assignment 9': 'CD',
      'Assignment 10': 'AA',
      'Assignment 11': 'AA',
      'Assignment 12': 'AD',
      'Assignment 13': 'FF',
      'Assignment 14': 'AA',
      'Assignment 15': 'BA',
      'Assignment 16': 'AA',
      'Assignment 17': 'AA',
      'Assignment 18': 'AB',
      'Assignment 19': 'AA',
      'Assignment 20': 'CA',
    },
    {
      'enrollmentNumber': '20',
      'Student': 'Grady Piper',
      'Assignment 1': 'CC',
      'Assignment 2': 'CC',
      'Assignment 3': 'AA',
      'Assignment 4': 'DD',
      'Assignment 5': 'DC',
      'Assignment 6': 'AA',
      'Assignment 7': 'AA',
      'Assignment 8': 'CD',
      'Assignment 9': 'AA',
      'Assignment 10': 'AA',
      'Assignment 11': 'AD',
      'Assignment 12': 'AA',
      'Assignment 13': 'AA',
      'Assignment 14': 'AA',
      'Assignment 15': 'FF',
      'Assignment 16': 'AA',
      'Assignment 17': 'BA',
      'Assignment 18': 'AB',
      'Assignment 19': 'AA',
      'Assignment 20': 'CA',
    },
    {
      'enrollmentNumber': '21',
      'Student': 'Jess Medina',
      'Assignment 1': 'AA',
      'Assignment 2': 'CC',
      'Assignment 3': 'DA',
      'Assignment 4': 'BB',
      'Assignment 5': 'AA',
      'Assignment 6': 'CC',
      'Assignment 7': 'AA',
      'Assignment 8': 'DC',
      'Assignment 9': 'AA',
      'Assignment 10': 'AA',
      'Assignment 11': 'DD',
      'Assignment 12': 'AA',
      'Assignment 13': 'AA',
      'Assignment 14': 'AB',
      'Assignment 15': 'AD',
      'Assignment 16': 'CA',
      'Assignment 17': 'AA',
      'Assignment 18': 'FF',
      'Assignment 19': 'BA',
      'Assignment 20': 'AA',
    },
    {
      'enrollmentNumber': '22',
      'Student': 'Benito Ray',
      'Assignment 1': 'AA',
      'Assignment 2': 'BB',
      'Assignment 3': 'DA',
      'Assignment 4': 'CC',
      'Assignment 5': 'AA',
      'Assignment 6': 'CC',
      'Assignment 7': 'AA',
      'Assignment 8': 'AA',
      'Assignment 9': 'AA',
      'Assignment 10': 'DC',
      'Assignment 11': 'AD',
      'Assignment 12': 'AA',
      'Assignment 13': 'AB',
      'Assignment 14': 'CA',
      'Assignment 15': 'DD',
      'Assignment 16': 'AA',
      'Assignment 17': 'AA',
      'Assignment 18': 'BA',
      'Assignment 19': 'AA',
      'Assignment 20': 'FF',
    },
    {
      'enrollmentNumber': '23',
      'Student': 'Kirby Miles',
      'Assignment 1': 'AA',
      'Assignment 2': 'AA',
      'Assignment 3': 'CC',
      'Assignment 4': 'CD',
      'Assignment 5': 'AA',
      'Assignment 6': 'AA',
      'Assignment 7': 'CC',
      'Assignment 8': 'AA',
      'Assignment 9': 'AA',
      'Assignment 10': 'AA',
      'Assignment 11': 'DC',
      'Assignment 12': 'DD',
      'Assignment 13': 'AA',
      'Assignment 14': 'AA',
      'Assignment 15': 'AD',
      'Assignment 16': 'AB',
      'Assignment 17': 'FF',
      'Assignment 18': 'CA',
      'Assignment 19': 'AA',
      'Assignment 20': 'BA',
    },
    {
      'enrollmentNumber': '24',
      'Student': 'Aimie Rooney',
      'Assignment 1': 'CC',
      'Assignment 2': 'CC',
      'Assignment 3': 'AA',
      'Assignment 4': 'AA',
      'Assignment 5': 'DD',
      'Assignment 6': 'AA',
      'Assignment 7': 'AA',
      'Assignment 8': 'DC',
      'Assignment 9': 'CD',
      'Assignment 10': 'AA',
      'Assignment 11': 'AA',
      'Assignment 12': 'AD',
      'Assignment 13': 'FF',
      'Assignment 14': 'AA',
      'Assignment 15': 'BA',
      'Assignment 16': 'AA',
      'Assignment 17': 'AA',
      'Assignment 18': 'AB',
      'Assignment 19': 'AA',
      'Assignment 20': 'CA',
    },
    {
      'enrollmentNumber': '25',
      'Student': 'Grady Piper',
      'Assignment 1': 'CC',
      'Assignment 2': 'CC',
      'Assignment 3': 'AA',
      'Assignment 4': 'DD',
      'Assignment 5': 'DC',
      'Assignment 6': 'AA',
      'Assignment 7': 'AA',
      'Assignment 8': 'CD',
      'Assignment 9': 'AA',
      'Assignment 10': 'AA',
      'Assignment 11': 'AD',
      'Assignment 12': 'AA',
      'Assignment 13': 'AA',
      'Assignment 14': 'AA',
      'Assignment 15': 'FF',
      'Assignment 16': 'AA',
      'Assignment 17': 'BA',
      'Assignment 18': 'AB',
      'Assignment 19': 'AA',
      'Assignment 20': 'CA',
    },
  ];

  displayedColumns: string[] = [
    'Student',
    'Assignment 1',
    'Assignment 2',
    'Assignment 3',
    'Assignment 4',
    'Assignment 5',
    'Assignment 6',
    'Assignment 7',
    'Assignment 8',
    'Assignment 9',
    'Assignment 10',
    'Assignment 11',
    'Assignment 12',
    'Assignment 13',
    'Assignment 14',
    'Assignment 15',
    'Assignment 16',
    'Assignment 17',
    'Assignment 18',
    'Assignment 19',
    'Assignment 20'
  ];
  displayAll: boolean = false;
  displayNone: boolean = false;
  selectedColumns: string[] = [];
  dataSource = new MatTableDataSource();


  displayColumnForm: FormGroup = new FormGroup({
    displayAll: new FormControl('', Validators.requiredTrue),
    displayNone: new FormControl('', Validators.requiredTrue)
  });

  constructor(private router: Router) { }

  ngOnInit(): void {
      this.selectedColumns = this.displayedColumns;

      this.dataSource = new MatTableDataSource(this.data);
    
    this.displayColumnForm.valueChanges.subscribe(value => {
      if(value.displayAll === true) {
        this.selectedColumns = this.displayedColumns;
      }

      if(value.displayNone === true) {
        this.selectedColumns = [];
      }
    })
  }

  setDataSourceAttributes() {
    this.dataSource.paginator = this.paginator;
    this.dataSource.sort = this.sort;
  }

  applyFilter(event: Event) {
    const filterValue = (event.target as HTMLInputElement).value;
    this.dataSource.filter = filterValue.trim().toLowerCase();
  }

  displayAllColumns = () => {
    if(this.displayAll === false) {
      this.displayNone = false; 
      this.selectedColumns = this.displayedColumns;
    }
  }

  displayNoColumns = () => {
    if(this.displayNone === false) {
      this.displayAll = false;
      this.selectedColumns = [];
    }
  }

  isSticky = (column) => {
    return column === 'Student' ? true : false;
  }

  navigateTo = (row) => {
    this.router.navigate(['student/' + row.enrollmentNumber]);
    // this.router.navigate(['student']);
  }
}
