import { UserPermission } from './../models/userRole.model';
import { Injectable } from '@angular/core';

@Injectable({
    providedIn: 'root'
})
export class StudentService {

  students: any = [
    {
      "studentId":"1001",
      "enrollmentNo":"68102",
      "name":"Jess",
      "lastName":"Medina",
      "grade":"1",
      "avgScore": 3.5,
      "major": "Maths",
      "gender":"Female",
      "image": "lady-1",
      "assignments":[
        {
          "assignmentId":"asgn1",
          "assignmentName":"Basics of Trigonometry",
          "assignmentWeightage":"7",
          "assignmentStartDt":"06/01/2020",
          "assignmentEndDt":"06/25/2020",
          "completionDt":"06/19/2020",
          "lessonName":"Trigonometry",
          "score": '3.4',
          "className": "Maths",
          "attempts": 1
        },
        {
          "assignmentId":"asgn2",
          "assignmentName":"Algebra",
          "assignmentWeightage":"7",
          "assignmentStartDt":"06/04/2020",
          "assignmentEndDt":"06/15/2020",
          "completionDt":"06/14/2020",
          "lessonName":"Mathematics",
          "score": '3.4',
          "className": "Maths",
          "attempts": 3
        },
        {
          "assignmentId":"asgn1",
          "assignmentName":"Chemistry - Liquid Solutions",
          "assignmentWeightage":"7",
          "assignmentStartDt":"06/01/2020",
          "assignmentEndDt":"06/25/2020",
          "completionDt":"06/19/2020",
          "lessonName":"Chemistry ",
          "score": '2.9',
          "className": "Chemistry",
          "attempts": 2
        },
        {
          "assignmentId":"asgn2",
          "assignmentName":"Algebra",
          "assignmentWeightage":"7",
          "assignmentStartDt":"06/04/2020",
          "assignmentEndDt":"06/15/2020",
          "completionDt":"06/14/2020",
          "lessonName":"Mathematics",
          "score": '3.4',
          "className": "Maths",
          "attempts": 3
        },
        {
          "assignmentId":"asgn1",
          "assignmentName":"Basics of Trigonometry",
          "assignmentWeightage":"7",
          "assignmentStartDt":"06/01/2020",
          "assignmentEndDt":"06/25/2020",
          "completionDt":"06/19/2020",
          "lessonName":"Trigonometry",
          "score": '4',
          "className": "Maths",
          "attempts": 1
        },
        {
          "assignmentId":"asgn2",
          "assignmentName":"Algebra",
          "assignmentWeightage":"7",
          "assignmentStartDt":"06/04/2020",
          "assignmentEndDt":"06/15/2020",
          "completionDt":"06/14/2020",
          "lessonName":"Mathematics",
          "score": '3.8',
          "className": "Maths",
          "attempts": 2
        },
        {
          "assignmentId":"asgn1",
          "assignmentName":"Basics of Trigonometry",
          "assignmentWeightage":"7",
          "assignmentStartDt":"06/01/2020",
          "assignmentEndDt":"06/25/2020",
          "completionDt":"06/19/2020",
          "lessonName":"Trigonometry",
          "score": '3.4',
          "className": "Maths",
          "attempts": 1
        },
        {
          "assignmentId":"asgn2",
          "assignmentName":"Algebra",
          "assignmentWeightage":"7",
          "assignmentStartDt":"06/04/2020",
          "assignmentEndDt":"06/15/2020",
          "completionDt":"06/14/2020",
          "lessonName":"Mathematics",
          "score": '3.4',
          "className": "Maths",
          "attempts": 3
        },
        {
          "assignmentId":"asgn1",
          "assignmentName":"Chemistry - Liquid Solutions",
          "assignmentWeightage":"7",
          "assignmentStartDt":"06/01/2020",
          "assignmentEndDt":"06/25/2020",
          "completionDt":"06/19/2020",
          "lessonName":"Chemistry ",
          "score": '2.9',
          "className": "Chemistry",
          "attempts": 2
        },
        {
          "assignmentId":"asgn2",
          "assignmentName":"Algebra",
          "assignmentWeightage":"7",
          "assignmentStartDt":"06/04/2020",
          "assignmentEndDt":"06/15/2020",
          "completionDt":"06/14/2020",
          "lessonName":"Mathematics",
          "score": '3.4',
          "className": "Maths",
          "attempts": 3
        },
        {
          "assignmentId":"asgn1",
          "assignmentName":"Basics of Trigonometry",
          "assignmentWeightage":"7",
          "assignmentStartDt":"06/01/2020",
          "assignmentEndDt":"06/25/2020",
          "completionDt":"06/19/2020",
          "lessonName":"Trigonometry",
          "score": '4',
          "className": "Maths",
          "attempts": 1
        },
        {
          "assignmentId":"asgn2",
          "assignmentName":"Algebra",
          "assignmentWeightage":"7",
          "assignmentStartDt":"06/04/2020",
          "assignmentEndDt":"06/15/2020",
          "completionDt":"06/14/2020",
          "lessonName":"Mathematics",
          "score": '3.8',
          "className": "Maths",
          "attempts": 2
        },
        {
          "assignmentId":"asgn1",
          "assignmentName":"Basics of Trigonometry",
          "assignmentWeightage":"7",
          "assignmentStartDt":"06/01/2020",
          "assignmentEndDt":"06/25/2020",
          "completionDt":"06/19/2020",
          "lessonName":"Trigonometry",
          "score": '3.4',
          "className": "Maths",
          "attempts": 1
        },
        {
          "assignmentId":"asgn2",
          "assignmentName":"Algebra",
          "assignmentWeightage":"7",
          "assignmentStartDt":"06/04/2020",
          "assignmentEndDt":"06/15/2020",
          "completionDt":"06/14/2020",
          "lessonName":"Mathematics",
          "score": '3.4',
          "className": "Maths",
          "attempts": 3
        },
        {
          "assignmentId":"asgn1",
          "assignmentName":"Chemistry - Liquid Solutions",
          "assignmentWeightage":"7",
          "assignmentStartDt":"06/01/2020",
          "assignmentEndDt":"06/25/2020",
          "completionDt":"06/19/2020",
          "lessonName":"Chemistry ",
          "score": '2.9',
          "className": "Chemistry",
          "attempts": 2
        },
        {
          "assignmentId":"asgn2",
          "assignmentName":"Algebra",
          "assignmentWeightage":"7",
          "assignmentStartDt":"06/04/2020",
          "assignmentEndDt":"06/15/2020",
          "completionDt":"06/14/2020",
          "lessonName":"Mathematics",
          "score": '3.4',
          "className": "Maths",
          "attempts": 3
        },
        {
          "assignmentId":"asgn1",
          "assignmentName":"Basics of Trigonometry",
          "assignmentWeightage":"7",
          "assignmentStartDt":"06/01/2020",
          "assignmentEndDt":"06/25/2020",
          "completionDt":"06/19/2020",
          "lessonName":"Trigonometry",
          "score": '4',
          "className": "Maths",
          "attempts": 1
        },
        {
          "assignmentId":"asgn2",
          "assignmentName":"Algebra",
          "assignmentWeightage":"7",
          "assignmentStartDt":"06/04/2020",
          "assignmentEndDt":"06/15/2020",
          "completionDt":"06/14/2020",
          "lessonName":"Mathematics",
          "score": '3.8',
          "className": "Maths",
          "attempts": 2
        },
        {
          "assignmentId":"asgn1",
          "assignmentName":"Basics of Trigonometry",
          "assignmentWeightage":"7",
          "assignmentStartDt":"06/01/2020",
          "assignmentEndDt":"06/25/2020",
          "completionDt":"06/19/2020",
          "lessonName":"Trigonometry",
          "score": '4',
          "className": "Maths",
          "attempts": 1
        },
        {
          "assignmentId":"asgn2",
          "assignmentName":"Algebra",
          "assignmentWeightage":"7",
          "assignmentStartDt":"06/04/2020",
          "assignmentEndDt":"06/15/2020",
          "completionDt":"06/14/2020",
          "lessonName":"Mathematics",
          "score": '3.8',
          "className": "Maths",
          "attempts": 2
        }
      ]
      },
      {
        "studentId":"1001",
        "enrollmentNo":"68102",
        "name":"Benito",
        "lastName":"Ray",
        "grade":"2",
        "avgScore": 3.5,
        "major": "Maths",
        "gender":"Male",
        "image": "guy-1",
        "assignments":[
          {
            "assignmentId":"asgn1",
            "assignmentName":"Basics of Trigonometry",
            "assignmentWeightage":"7",
            "assignmentStartDt":"06/01/2020",
            "assignmentEndDt":"06/25/2020",
            "completionDt":"06/19/2020",
            "lessonName":"Trigonometry",
            "score": '3.4',
            "className": "Maths",
            "attempts": 1
          },
          {
            "assignmentId":"asgn2",
            "assignmentName":"Algebra",
            "assignmentWeightage":"7",
            "assignmentStartDt":"06/04/2020",
            "assignmentEndDt":"06/15/2020",
            "completionDt":"06/14/2020",
            "lessonName":"Mathematics",
            "score": '3.4',
            "className": "Maths",
            "attempts": 3
          },
          {
            "assignmentId":"asgn1",
            "assignmentName":"Chemistry - Liquid Solutions",
            "assignmentWeightage":"7",
            "assignmentStartDt":"06/01/2020",
            "assignmentEndDt":"06/25/2020",
            "completionDt":"06/19/2020",
            "lessonName":"Chemistry ",
            "score": '2.9',
            "className": "Chemistry",
            "attempts": 2
          },
          {
            "assignmentId":"asgn2",
            "assignmentName":"Algebra",
            "assignmentWeightage":"7",
            "assignmentStartDt":"06/04/2020",
            "assignmentEndDt":"06/15/2020",
            "completionDt":"06/14/2020",
            "lessonName":"Mathematics",
            "score": '3.4',
            "className": "Maths",
            "attempts": 3
          },
          {
            "assignmentId":"asgn1",
            "assignmentName":"Basics of Trigonometry",
            "assignmentWeightage":"7",
            "assignmentStartDt":"06/01/2020",
            "assignmentEndDt":"06/25/2020",
            "completionDt":"06/19/2020",
            "lessonName":"Trigonometry",
            "score": '4',
            "className": "Maths",
            "attempts": 1
          },
          {
            "assignmentId":"asgn2",
            "assignmentName":"Algebra",
            "assignmentWeightage":"7",
            "assignmentStartDt":"06/04/2020",
            "assignmentEndDt":"06/15/2020",
            "completionDt":"06/14/2020",
            "lessonName":"Mathematics",
            "score": '3.8',
            "className": "Maths",
            "attempts": 2
          },
          {
            "assignmentId":"asgn1",
            "assignmentName":"Basics of Trigonometry",
            "assignmentWeightage":"7",
            "assignmentStartDt":"06/01/2020",
            "assignmentEndDt":"06/25/2020",
            "completionDt":"06/19/2020",
            "lessonName":"Trigonometry",
            "score": '3.4',
            "className": "Maths",
            "attempts": 1
          },
          {
            "assignmentId":"asgn2",
            "assignmentName":"Algebra",
            "assignmentWeightage":"7",
            "assignmentStartDt":"06/04/2020",
            "assignmentEndDt":"06/15/2020",
            "completionDt":"06/14/2020",
            "lessonName":"Mathematics",
            "score": '3.4',
            "className": "Maths",
            "attempts": 3
          },
          {
            "assignmentId":"asgn1",
            "assignmentName":"Chemistry - Liquid Solutions",
            "assignmentWeightage":"7",
            "assignmentStartDt":"06/01/2020",
            "assignmentEndDt":"06/25/2020",
            "completionDt":"06/19/2020",
            "lessonName":"Chemistry ",
            "score": '2.9',
            "className": "Chemistry",
            "attempts": 2
          },
          {
            "assignmentId":"asgn2",
            "assignmentName":"Algebra",
            "assignmentWeightage":"7",
            "assignmentStartDt":"06/04/2020",
            "assignmentEndDt":"06/15/2020",
            "completionDt":"06/14/2020",
            "lessonName":"Mathematics",
            "score": '3.4',
            "className": "Maths",
            "attempts": 3
          },
          {
            "assignmentId":"asgn1",
            "assignmentName":"Basics of Trigonometry",
            "assignmentWeightage":"7",
            "assignmentStartDt":"06/01/2020",
            "assignmentEndDt":"06/25/2020",
            "completionDt":"06/19/2020",
            "lessonName":"Trigonometry",
            "score": '4',
            "className": "Maths",
            "attempts": 1
          },
          {
            "assignmentId":"asgn2",
            "assignmentName":"Algebra",
            "assignmentWeightage":"7",
            "assignmentStartDt":"06/04/2020",
            "assignmentEndDt":"06/15/2020",
            "completionDt":"06/14/2020",
            "lessonName":"Mathematics",
            "score": '3.8',
            "className": "Maths",
            "attempts": 2
          },
          {
            "assignmentId":"asgn1",
            "assignmentName":"Basics of Trigonometry",
            "assignmentWeightage":"7",
            "assignmentStartDt":"06/01/2020",
            "assignmentEndDt":"06/25/2020",
            "completionDt":"06/19/2020",
            "lessonName":"Trigonometry",
            "score": '3.4',
            "className": "Maths",
            "attempts": 1
          },
          {
            "assignmentId":"asgn2",
            "assignmentName":"Algebra",
            "assignmentWeightage":"7",
            "assignmentStartDt":"06/04/2020",
            "assignmentEndDt":"06/15/2020",
            "completionDt":"06/14/2020",
            "lessonName":"Mathematics",
            "score": '3.4',
            "className": "Maths",
            "attempts": 3
          },
          {
            "assignmentId":"asgn1",
            "assignmentName":"Chemistry - Liquid Solutions",
            "assignmentWeightage":"7",
            "assignmentStartDt":"06/01/2020",
            "assignmentEndDt":"06/25/2020",
            "completionDt":"06/19/2020",
            "lessonName":"Chemistry ",
            "score": '2.9',
            "className": "Chemistry",
            "attempts": 2
          },
          {
            "assignmentId":"asgn2",
            "assignmentName":"Algebra",
            "assignmentWeightage":"7",
            "assignmentStartDt":"06/04/2020",
            "assignmentEndDt":"06/15/2020",
            "completionDt":"06/14/2020",
            "lessonName":"Mathematics",
            "score": '3.4',
            "className": "Maths",
            "attempts": 3
          },
          {
            "assignmentId":"asgn1",
            "assignmentName":"Basics of Trigonometry",
            "assignmentWeightage":"7",
            "assignmentStartDt":"06/01/2020",
            "assignmentEndDt":"06/25/2020",
            "completionDt":"06/19/2020",
            "lessonName":"Trigonometry",
            "score": '4',
            "className": "Maths",
            "attempts": 1
          },
          {
            "assignmentId":"asgn2",
            "assignmentName":"Algebra",
            "assignmentWeightage":"7",
            "assignmentStartDt":"06/04/2020",
            "assignmentEndDt":"06/15/2020",
            "completionDt":"06/14/2020",
            "lessonName":"Mathematics",
            "score": '3.8',
            "className": "Maths",
            "attempts": 2
          },
          {
            "assignmentId":"asgn1",
            "assignmentName":"Basics of Trigonometry",
            "assignmentWeightage":"7",
            "assignmentStartDt":"06/01/2020",
            "assignmentEndDt":"06/25/2020",
            "completionDt":"06/19/2020",
            "lessonName":"Trigonometry",
            "score": '4',
            "className": "Maths",
            "attempts": 1
          },
          {
            "assignmentId":"asgn2",
            "assignmentName":"Algebra",
            "assignmentWeightage":"7",
            "assignmentStartDt":"06/04/2020",
            "assignmentEndDt":"06/15/2020",
            "completionDt":"06/14/2020",
            "lessonName":"Mathematics",
            "score": '3.8',
            "className": "Maths",
            "attempts": 2
          }
        ]
      },
      {
        "studentId":"1001",
        "enrollmentNo":"68102",
        "name":"Kirby",
        "lastName":"Miles",
        "grade":"3",
        "avgScore": 3.5,
        "major": "Maths",
        "gender":"Female",
        "image": "guy-2",
        "assignments":[
          {
            "assignmentId":"asgn1",
            "assignmentName":"Basics of Trigonometry",
            "assignmentWeightage":"7",
            "assignmentStartDt":"06/01/2020",
            "assignmentEndDt":"06/25/2020",
            "completionDt":"06/19/2020",
            "lessonName":"Trigonometry",
            "score": '3.4',
            "className": "Maths",
            "attempts": 1
          },
          {
            "assignmentId":"asgn2",
            "assignmentName":"Algebra",
            "assignmentWeightage":"7",
            "assignmentStartDt":"06/04/2020",
            "assignmentEndDt":"06/15/2020",
            "completionDt":"06/14/2020",
            "lessonName":"Mathematics",
            "score": '3.4',
            "className": "Maths",
            "attempts": 3
          },
          {
            "assignmentId":"asgn1",
            "assignmentName":"Chemistry - Liquid Solutions",
            "assignmentWeightage":"7",
            "assignmentStartDt":"06/01/2020",
            "assignmentEndDt":"06/25/2020",
            "completionDt":"06/19/2020",
            "lessonName":"Chemistry ",
            "score": '2.9',
            "className": "Chemistry",
            "attempts": 2
          },
          {
            "assignmentId":"asgn2",
            "assignmentName":"Algebra",
            "assignmentWeightage":"7",
            "assignmentStartDt":"06/04/2020",
            "assignmentEndDt":"06/15/2020",
            "completionDt":"06/14/2020",
            "lessonName":"Mathematics",
            "score": '3.4',
            "className": "Maths",
            "attempts": 3
          },
          {
            "assignmentId":"asgn1",
            "assignmentName":"Basics of Trigonometry",
            "assignmentWeightage":"7",
            "assignmentStartDt":"06/01/2020",
            "assignmentEndDt":"06/25/2020",
            "completionDt":"06/19/2020",
            "lessonName":"Trigonometry",
            "score": '4',
            "className": "Maths",
            "attempts": 1
          },
          {
            "assignmentId":"asgn2",
            "assignmentName":"Algebra",
            "assignmentWeightage":"7",
            "assignmentStartDt":"06/04/2020",
            "assignmentEndDt":"06/15/2020",
            "completionDt":"06/14/2020",
            "lessonName":"Mathematics",
            "score": '3.8',
            "className": "Maths",
            "attempts": 2
          },
          {
            "assignmentId":"asgn1",
            "assignmentName":"Basics of Trigonometry",
            "assignmentWeightage":"7",
            "assignmentStartDt":"06/01/2020",
            "assignmentEndDt":"06/25/2020",
            "completionDt":"06/19/2020",
            "lessonName":"Trigonometry",
            "score": '3.4',
            "className": "Maths",
            "attempts": 1
          },
          {
            "assignmentId":"asgn2",
            "assignmentName":"Algebra",
            "assignmentWeightage":"7",
            "assignmentStartDt":"06/04/2020",
            "assignmentEndDt":"06/15/2020",
            "completionDt":"06/14/2020",
            "lessonName":"Mathematics",
            "score": '3.4',
            "className": "Maths",
            "attempts": 3
          },
          {
            "assignmentId":"asgn1",
            "assignmentName":"Chemistry - Liquid Solutions",
            "assignmentWeightage":"7",
            "assignmentStartDt":"06/01/2020",
            "assignmentEndDt":"06/25/2020",
            "completionDt":"06/19/2020",
            "lessonName":"Chemistry ",
            "score": '2.9',
            "className": "Chemistry",
            "attempts": 2
          },
          {
            "assignmentId":"asgn2",
            "assignmentName":"Algebra",
            "assignmentWeightage":"7",
            "assignmentStartDt":"06/04/2020",
            "assignmentEndDt":"06/15/2020",
            "completionDt":"06/14/2020",
            "lessonName":"Mathematics",
            "score": '3.4',
            "className": "Maths",
            "attempts": 3
          },
          {
            "assignmentId":"asgn1",
            "assignmentName":"Basics of Trigonometry",
            "assignmentWeightage":"7",
            "assignmentStartDt":"06/01/2020",
            "assignmentEndDt":"06/25/2020",
            "completionDt":"06/19/2020",
            "lessonName":"Trigonometry",
            "score": '4',
            "className": "Maths",
            "attempts": 1
          },
          {
            "assignmentId":"asgn2",
            "assignmentName":"Algebra",
            "assignmentWeightage":"7",
            "assignmentStartDt":"06/04/2020",
            "assignmentEndDt":"06/15/2020",
            "completionDt":"06/14/2020",
            "lessonName":"Mathematics",
            "score": '3.8',
            "className": "Maths",
            "attempts": 2
          },
          {
            "assignmentId":"asgn1",
            "assignmentName":"Basics of Trigonometry",
            "assignmentWeightage":"7",
            "assignmentStartDt":"06/01/2020",
            "assignmentEndDt":"06/25/2020",
            "completionDt":"06/19/2020",
            "lessonName":"Trigonometry",
            "score": '3.4',
            "className": "Maths",
            "attempts": 1
          },
          {
            "assignmentId":"asgn2",
            "assignmentName":"Algebra",
            "assignmentWeightage":"7",
            "assignmentStartDt":"06/04/2020",
            "assignmentEndDt":"06/15/2020",
            "completionDt":"06/14/2020",
            "lessonName":"Mathematics",
            "score": '3.4',
            "className": "Maths",
            "attempts": 3
          },
          {
            "assignmentId":"asgn1",
            "assignmentName":"Chemistry - Liquid Solutions",
            "assignmentWeightage":"7",
            "assignmentStartDt":"06/01/2020",
            "assignmentEndDt":"06/25/2020",
            "completionDt":"06/19/2020",
            "lessonName":"Chemistry ",
            "score": '2.9',
            "className": "Chemistry",
            "attempts": 2
          },
          {
            "assignmentId":"asgn2",
            "assignmentName":"Algebra",
            "assignmentWeightage":"7",
            "assignmentStartDt":"06/04/2020",
            "assignmentEndDt":"06/15/2020",
            "completionDt":"06/14/2020",
            "lessonName":"Mathematics",
            "score": '3.4',
            "className": "Maths",
            "attempts": 3
          },
          {
            "assignmentId":"asgn1",
            "assignmentName":"Basics of Trigonometry",
            "assignmentWeightage":"7",
            "assignmentStartDt":"06/01/2020",
            "assignmentEndDt":"06/25/2020",
            "completionDt":"06/19/2020",
            "lessonName":"Trigonometry",
            "score": '4',
            "className": "Maths",
            "attempts": 1
          },
          {
            "assignmentId":"asgn2",
            "assignmentName":"Algebra",
            "assignmentWeightage":"7",
            "assignmentStartDt":"06/04/2020",
            "assignmentEndDt":"06/15/2020",
            "completionDt":"06/14/2020",
            "lessonName":"Mathematics",
            "score": '3.8',
            "className": "Maths",
            "attempts": 2
          },
          {
            "assignmentId":"asgn1",
            "assignmentName":"Basics of Trigonometry",
            "assignmentWeightage":"7",
            "assignmentStartDt":"06/01/2020",
            "assignmentEndDt":"06/25/2020",
            "completionDt":"06/19/2020",
            "lessonName":"Trigonometry",
            "score": '4',
            "className": "Maths",
            "attempts": 1
          },
          {
            "assignmentId":"asgn2",
            "assignmentName":"Algebra",
            "assignmentWeightage":"7",
            "assignmentStartDt":"06/04/2020",
            "assignmentEndDt":"06/15/2020",
            "completionDt":"06/14/2020",
            "lessonName":"Mathematics",
            "score": '3.8',
            "className": "Maths",
            "attempts": 2
          }
        ]
      },
      {
        "studentId":"1001",
        "enrollmentNo":"68102",
        "name":"Aimie",
        "lastName":"Rooney",
        "grade":"4",
        "avgScore": 3.5,
        "major": "Maths",
        "gender":"Female",
        "image": "lady-2",
        "assignments":[
          {
            "assignmentId":"asgn1",
            "assignmentName":"Basics of Trigonometry",
            "assignmentWeightage":"7",
            "assignmentStartDt":"06/01/2020",
            "assignmentEndDt":"06/25/2020",
            "completionDt":"06/19/2020",
            "lessonName":"Trigonometry",
            "score": '3.4',
            "className": "Maths",
            "attempts": 1
          },
          {
            "assignmentId":"asgn2",
            "assignmentName":"Algebra",
            "assignmentWeightage":"7",
            "assignmentStartDt":"06/04/2020",
            "assignmentEndDt":"06/15/2020",
            "completionDt":"06/14/2020",
            "lessonName":"Mathematics",
            "score": '3.4',
            "className": "Maths",
            "attempts": 3
          },
          {
            "assignmentId":"asgn1",
            "assignmentName":"Chemistry - Liquid Solutions",
            "assignmentWeightage":"7",
            "assignmentStartDt":"06/01/2020",
            "assignmentEndDt":"06/25/2020",
            "completionDt":"06/19/2020",
            "lessonName":"Chemistry ",
            "score": '2.9',
            "className": "Chemistry",
            "attempts": 2
          },
          {
            "assignmentId":"asgn2",
            "assignmentName":"Algebra",
            "assignmentWeightage":"7",
            "assignmentStartDt":"06/04/2020",
            "assignmentEndDt":"06/15/2020",
            "completionDt":"06/14/2020",
            "lessonName":"Mathematics",
            "score": '3.4',
            "className": "Maths",
            "attempts": 3
          },
          {
            "assignmentId":"asgn1",
            "assignmentName":"Basics of Trigonometry",
            "assignmentWeightage":"7",
            "assignmentStartDt":"06/01/2020",
            "assignmentEndDt":"06/25/2020",
            "completionDt":"06/19/2020",
            "lessonName":"Trigonometry",
            "score": '4',
            "className": "Maths",
            "attempts": 1
          },
          {
            "assignmentId":"asgn2",
            "assignmentName":"Algebra",
            "assignmentWeightage":"7",
            "assignmentStartDt":"06/04/2020",
            "assignmentEndDt":"06/15/2020",
            "completionDt":"06/14/2020",
            "lessonName":"Mathematics",
            "score": '3.8',
            "className": "Maths",
            "attempts": 2
          },
          {
            "assignmentId":"asgn1",
            "assignmentName":"Basics of Trigonometry",
            "assignmentWeightage":"7",
            "assignmentStartDt":"06/01/2020",
            "assignmentEndDt":"06/25/2020",
            "completionDt":"06/19/2020",
            "lessonName":"Trigonometry",
            "score": '3.4',
            "className": "Maths",
            "attempts": 1
          },
          {
            "assignmentId":"asgn2",
            "assignmentName":"Algebra",
            "assignmentWeightage":"7",
            "assignmentStartDt":"06/04/2020",
            "assignmentEndDt":"06/15/2020",
            "completionDt":"06/14/2020",
            "lessonName":"Mathematics",
            "score": '3.4',
            "className": "Maths",
            "attempts": 3
          },
          {
            "assignmentId":"asgn1",
            "assignmentName":"Chemistry - Liquid Solutions",
            "assignmentWeightage":"7",
            "assignmentStartDt":"06/01/2020",
            "assignmentEndDt":"06/25/2020",
            "completionDt":"06/19/2020",
            "lessonName":"Chemistry ",
            "score": '2.9',
            "className": "Chemistry",
            "attempts": 2
          },
          {
            "assignmentId":"asgn2",
            "assignmentName":"Algebra",
            "assignmentWeightage":"7",
            "assignmentStartDt":"06/04/2020",
            "assignmentEndDt":"06/15/2020",
            "completionDt":"06/14/2020",
            "lessonName":"Mathematics",
            "score": '3.4',
            "className": "Maths",
            "attempts": 3
          },
          {
            "assignmentId":"asgn1",
            "assignmentName":"Basics of Trigonometry",
            "assignmentWeightage":"7",
            "assignmentStartDt":"06/01/2020",
            "assignmentEndDt":"06/25/2020",
            "completionDt":"06/19/2020",
            "lessonName":"Trigonometry",
            "score": '4',
            "className": "Maths",
            "attempts": 1
          },
          {
            "assignmentId":"asgn2",
            "assignmentName":"Algebra",
            "assignmentWeightage":"7",
            "assignmentStartDt":"06/04/2020",
            "assignmentEndDt":"06/15/2020",
            "completionDt":"06/14/2020",
            "lessonName":"Mathematics",
            "score": '3.8',
            "className": "Maths",
            "attempts": 2
          },
          {
            "assignmentId":"asgn1",
            "assignmentName":"Basics of Trigonometry",
            "assignmentWeightage":"7",
            "assignmentStartDt":"06/01/2020",
            "assignmentEndDt":"06/25/2020",
            "completionDt":"06/19/2020",
            "lessonName":"Trigonometry",
            "score": '3.4',
            "className": "Maths",
            "attempts": 1
          },
          {
            "assignmentId":"asgn2",
            "assignmentName":"Algebra",
            "assignmentWeightage":"7",
            "assignmentStartDt":"06/04/2020",
            "assignmentEndDt":"06/15/2020",
            "completionDt":"06/14/2020",
            "lessonName":"Mathematics",
            "score": '3.4',
            "className": "Maths",
            "attempts": 3
          },
          {
            "assignmentId":"asgn1",
            "assignmentName":"Chemistry - Liquid Solutions",
            "assignmentWeightage":"7",
            "assignmentStartDt":"06/01/2020",
            "assignmentEndDt":"06/25/2020",
            "completionDt":"06/19/2020",
            "lessonName":"Chemistry ",
            "score": '2.9',
            "className": "Chemistry",
            "attempts": 2
          },
          {
            "assignmentId":"asgn2",
            "assignmentName":"Algebra",
            "assignmentWeightage":"7",
            "assignmentStartDt":"06/04/2020",
            "assignmentEndDt":"06/15/2020",
            "completionDt":"06/14/2020",
            "lessonName":"Mathematics",
            "score": '3.4',
            "className": "Maths",
            "attempts": 3
          },
          {
            "assignmentId":"asgn1",
            "assignmentName":"Basics of Trigonometry",
            "assignmentWeightage":"7",
            "assignmentStartDt":"06/01/2020",
            "assignmentEndDt":"06/25/2020",
            "completionDt":"06/19/2020",
            "lessonName":"Trigonometry",
            "score": '4',
            "className": "Maths",
            "attempts": 1
          },
          {
            "assignmentId":"asgn2",
            "assignmentName":"Algebra",
            "assignmentWeightage":"7",
            "assignmentStartDt":"06/04/2020",
            "assignmentEndDt":"06/15/2020",
            "completionDt":"06/14/2020",
            "lessonName":"Mathematics",
            "score": '3.8',
            "className": "Maths",
            "attempts": 2
          },
          {
            "assignmentId":"asgn1",
            "assignmentName":"Basics of Trigonometry",
            "assignmentWeightage":"7",
            "assignmentStartDt":"06/01/2020",
            "assignmentEndDt":"06/25/2020",
            "completionDt":"06/19/2020",
            "lessonName":"Trigonometry",
            "score": '4',
            "className": "Maths",
            "attempts": 1
          },
          {
            "assignmentId":"asgn2",
            "assignmentName":"Algebra",
            "assignmentWeightage":"7",
            "assignmentStartDt":"06/04/2020",
            "assignmentEndDt":"06/15/2020",
            "completionDt":"06/14/2020",
            "lessonName":"Mathematics",
            "score": '3.8',
            "className": "Maths",
            "attempts": 2
          }
        ]
      },
      {
        "studentId":"1001",
        "enrollmentNo":"68102",
        "name":"Rebecca",
        "lastName":"Smith",
        "grade":"5",
        "avgScore": 3.5,
        "major": "Maths",
        "gender":"Female",
        "image": "lady-1",
        "assignments":[
          {
            "assignmentId":"asgn1",
            "assignmentName":"Basics of Trigonometry",
            "assignmentWeightage":"7",
            "assignmentStartDt":"06/01/2020",
            "assignmentEndDt":"06/25/2020",
            "completionDt":"06/19/2020",
            "lessonName":"Trigonometry",
            "score": '3.4',
            "className": "Maths",
            "attempts": 1
          },
          {
            "assignmentId":"asgn2",
            "assignmentName":"Algebra",
            "assignmentWeightage":"7",
            "assignmentStartDt":"06/04/2020",
            "assignmentEndDt":"06/15/2020",
            "completionDt":"06/14/2020",
            "lessonName":"Mathematics",
            "score": '3.4',
            "className": "Maths",
            "attempts": 3
          },
          {
            "assignmentId":"asgn1",
            "assignmentName":"Chemistry - Liquid Solutions",
            "assignmentWeightage":"7",
            "assignmentStartDt":"06/01/2020",
            "assignmentEndDt":"06/25/2020",
            "completionDt":"06/19/2020",
            "lessonName":"Chemistry ",
            "score": '2.9',
            "className": "Chemistry",
            "attempts": 2
          },
          {
            "assignmentId":"asgn2",
            "assignmentName":"Algebra",
            "assignmentWeightage":"7",
            "assignmentStartDt":"06/04/2020",
            "assignmentEndDt":"06/15/2020",
            "completionDt":"06/14/2020",
            "lessonName":"Mathematics",
            "score": '3.4',
            "className": "Maths",
            "attempts": 3
          },
          {
            "assignmentId":"asgn1",
            "assignmentName":"Basics of Trigonometry",
            "assignmentWeightage":"7",
            "assignmentStartDt":"06/01/2020",
            "assignmentEndDt":"06/25/2020",
            "completionDt":"06/19/2020",
            "lessonName":"Trigonometry",
            "score": '4',
            "className": "Maths",
            "attempts": 1
          },
          {
            "assignmentId":"asgn2",
            "assignmentName":"Algebra",
            "assignmentWeightage":"7",
            "assignmentStartDt":"06/04/2020",
            "assignmentEndDt":"06/15/2020",
            "completionDt":"06/14/2020",
            "lessonName":"Mathematics",
            "score": '3.8',
            "className": "Maths",
            "attempts": 2
          },
          {
            "assignmentId":"asgn1",
            "assignmentName":"Basics of Trigonometry",
            "assignmentWeightage":"7",
            "assignmentStartDt":"06/01/2020",
            "assignmentEndDt":"06/25/2020",
            "completionDt":"06/19/2020",
            "lessonName":"Trigonometry",
            "score": '3.4',
            "className": "Maths",
            "attempts": 1
          },
          {
            "assignmentId":"asgn2",
            "assignmentName":"Algebra",
            "assignmentWeightage":"7",
            "assignmentStartDt":"06/04/2020",
            "assignmentEndDt":"06/15/2020",
            "completionDt":"06/14/2020",
            "lessonName":"Mathematics",
            "score": '3.4',
            "className": "Maths",
            "attempts": 3
          },
          {
            "assignmentId":"asgn1",
            "assignmentName":"Chemistry - Liquid Solutions",
            "assignmentWeightage":"7",
            "assignmentStartDt":"06/01/2020",
            "assignmentEndDt":"06/25/2020",
            "completionDt":"06/19/2020",
            "lessonName":"Chemistry ",
            "score": '2.9',
            "className": "Chemistry",
            "attempts": 2
          },
          {
            "assignmentId":"asgn2",
            "assignmentName":"Algebra",
            "assignmentWeightage":"7",
            "assignmentStartDt":"06/04/2020",
            "assignmentEndDt":"06/15/2020",
            "completionDt":"06/14/2020",
            "lessonName":"Mathematics",
            "score": '3.4',
            "className": "Maths",
            "attempts": 3
          },
          {
            "assignmentId":"asgn1",
            "assignmentName":"Basics of Trigonometry",
            "assignmentWeightage":"7",
            "assignmentStartDt":"06/01/2020",
            "assignmentEndDt":"06/25/2020",
            "completionDt":"06/19/2020",
            "lessonName":"Trigonometry",
            "score": '4',
            "className": "Maths",
            "attempts": 1
          },
          {
            "assignmentId":"asgn2",
            "assignmentName":"Algebra",
            "assignmentWeightage":"7",
            "assignmentStartDt":"06/04/2020",
            "assignmentEndDt":"06/15/2020",
            "completionDt":"06/14/2020",
            "lessonName":"Mathematics",
            "score": '3.8',
            "className": "Maths",
            "attempts": 2
          },
          {
            "assignmentId":"asgn1",
            "assignmentName":"Basics of Trigonometry",
            "assignmentWeightage":"7",
            "assignmentStartDt":"06/01/2020",
            "assignmentEndDt":"06/25/2020",
            "completionDt":"06/19/2020",
            "lessonName":"Trigonometry",
            "score": '3.4',
            "className": "Maths",
            "attempts": 1
          },
          {
            "assignmentId":"asgn2",
            "assignmentName":"Algebra",
            "assignmentWeightage":"7",
            "assignmentStartDt":"06/04/2020",
            "assignmentEndDt":"06/15/2020",
            "completionDt":"06/14/2020",
            "lessonName":"Mathematics",
            "score": '3.4',
            "className": "Maths",
            "attempts": 3
          },
          {
            "assignmentId":"asgn1",
            "assignmentName":"Chemistry - Liquid Solutions",
            "assignmentWeightage":"7",
            "assignmentStartDt":"06/01/2020",
            "assignmentEndDt":"06/25/2020",
            "completionDt":"06/19/2020",
            "lessonName":"Chemistry ",
            "score": '2.9',
            "className": "Chemistry",
            "attempts": 2
          },
          {
            "assignmentId":"asgn2",
            "assignmentName":"Algebra",
            "assignmentWeightage":"7",
            "assignmentStartDt":"06/04/2020",
            "assignmentEndDt":"06/15/2020",
            "completionDt":"06/14/2020",
            "lessonName":"Mathematics",
            "score": '3.4',
            "className": "Maths",
            "attempts": 3
          },
          {
            "assignmentId":"asgn1",
            "assignmentName":"Basics of Trigonometry",
            "assignmentWeightage":"7",
            "assignmentStartDt":"06/01/2020",
            "assignmentEndDt":"06/25/2020",
            "completionDt":"06/19/2020",
            "lessonName":"Trigonometry",
            "score": '4',
            "className": "Maths",
            "attempts": 1
          },
          {
            "assignmentId":"asgn2",
            "assignmentName":"Algebra",
            "assignmentWeightage":"7",
            "assignmentStartDt":"06/04/2020",
            "assignmentEndDt":"06/15/2020",
            "completionDt":"06/14/2020",
            "lessonName":"Mathematics",
            "score": '3.8',
            "className": "Maths",
            "attempts": 2
          },
          {
            "assignmentId":"asgn1",
            "assignmentName":"Basics of Trigonometry",
            "assignmentWeightage":"7",
            "assignmentStartDt":"06/01/2020",
            "assignmentEndDt":"06/25/2020",
            "completionDt":"06/19/2020",
            "lessonName":"Trigonometry",
            "score": '4',
            "className": "Maths",
            "attempts": 1
          },
          {
            "assignmentId":"asgn2",
            "assignmentName":"Algebra",
            "assignmentWeightage":"7",
            "assignmentStartDt":"06/04/2020",
            "assignmentEndDt":"06/15/2020",
            "completionDt":"06/14/2020",
            "lessonName":"Mathematics",
            "score": '3.8',
            "className": "Maths",
            "attempts": 2
          }
        ]
      }
    ]
    
    constructor() { }

    getStudent(id) {
      if(id < 6) {
        return this.students[id-1];
      } else {
        return this.students[0];
      }
    }
}
